### ISSUE TITLE
ReferenceError: TextDecoder is not defined

### ISSUE THREAD

**Issue by Cyperwu** [radialogica/dicom-character-set#1]
Hi,

I tested the non-promise api of your package and got an Error: `ReferenceError: TextDecoder is not defined`.
Diving into your code I found a `new TextDecoder()` line 106 in `convert-bytes.js`.
Hoping for reply

Cyper

**Comment by yagni** [comment]
Hi Cyper, thanks for trying it out! Are you doing this on node.js by any chance? Node has a different name for the TextDecoder so it won't work as-is unfortunately. It'd be trivial to switch between the node decoder (I think it's called Buffer) and TextDecoder if you want to make a pull request; otherwise, I'll try to get to that soon.

**Comment by Cyperwu** [comment]
Hi @yagni,
Ok, I'll try for a PR

**Comment by yagni** [comment]
Fixed in version 1.0.2. Sorry for the delay!
