### ISSUE TITLE
Hi, I had a problem translating the patient’s name into Cyrillic

### ISSUE THREAD

**Issue by arsenarustamyan** [radialogica/dicom-character-set#3]
There is a wild shot with the tag (0008,0005) - the following value of "ISO 2022 IR 6, IS" and I try to convert this value to krillitsa and it doesn’t work

**Comment by yagni** [comment]
That doesn't appear to be a valid Specific Character Set string. What's the ", IS" part supposed to do? Also, if your data is encoded in Cyrillic without code extensions (probably the most likely scenario), try passing "ISO_IR 144" as the first argument rather than "ISO 2022 IR 6", which is the default ASCII character set--a non-Cyrillic one. It really depends on how the source software encoded it. If ISO_IR 144 doesn't work, can you attach some anonymized DICOM that has been anonymized to the same Cyrillic encoding you're using?

**Comment by yagni** [comment]
I'm going to go ahead and close this @arustamyan-developer . Feel free to reopen if you want to troubleshoot this further.
